<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.4 setup script
 * Date: Tue, 04 Dec 2012 10:16:23 -0500
 */

/* Servers configuration */
$i = 0;

/* Server: Password Manager [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Password Manager';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '50be13bd7f6e71.84351665';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>